# Generated by Django 6.1.1 on 2026-09-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_marketcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='trade',
            name='payout_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('WIN', 'WIN'), ('LOSS', 'LOSS')], default='OPEN', max_length=10),
        ),
    ]
