# Generated by Django 6.1.1 on 2026-09-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_tradingaccount_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='trading_ban_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='trading_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='withdrawal_ban_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='withdrawal_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
