# Generated by Django 6.1.1 on 2026-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_tradingaccount_trading_ban_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='closing_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
