# Generated by Django 6.1.1 on 2026-09-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_trade_closing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='marketcontrol',
            name='asset',
            field=models.CharField(default='BTC/USD', max_length=20),
        ),
        migrations.AddField(
            model_name='marketcontrol',
            name='pair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_control', to='trading.tradingpair'),
        ),
        migrations.AddField(
            model_name='trade',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.tradingpair'),
        ),
    ]
