# Generated by Django 6.1.1 on 2026-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_tradingpair_alter_marketcontrol_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
