# Generated by Django 6.1.1 on 2026-09-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_transaction_account_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_enabled', models.BooleanField(default=True)),
                ('withdrawals_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
