# Generated by Django 6.1.1 on 2026-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=20, unique=True)),
                ('direction', models.CharField(choices=[('AUTO', 'AUTO'), ('UP', 'UP'), ('DOWN', 'DOWN')], default='AUTO', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
