# Generated by Django 6.1.1 on 2026-09-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_trade_duration_seconds_trade_payout_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='credit_score',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
