# Generated by Django 6.1.1 on 2026-09-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_platformcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='balance_pkr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='balance_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
