# Generated by Django 6.1.1 on 2026-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_tradingaccount_balance_pkr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR')], default='USD', max_length=3),
        ),
    ]
